### PR TITLE
Update facilitationTechniques.markdown

### PR DESCRIPTION
**Pull request by ppatchig**
Added SWOT, which is good retrospective facilitation technique as per my understanding.

### CODE REVIEW

**Comment by ppatchig** [comment]
Checking

**Comment by ppatchig** [comment]
Checking how this works.

**Comment by fahmyboy** [comment]
have you figured it out?

**Comment by ppatchig** [comment]
I used GIT in the past. I haven't used GitHub much. Trying to figure out.
Are you recommending using GitHub Desktop?
As per my understanding, I can't download at work

Thanks,
Prameela

**Pull request closed without merging**
