### PR TITLE
short explaination of Shu Ha Ri, for context

### PR DESCRIPTION
**Pull request by timborn**

### CODE REVIEW

**Review by eross529 — COMMENTED** [review]
Thanks Tim!

**Review by fahmyboy — APPROVED** [review]

**Comment by eross529** [comment]
Hey Amhad - looks like Readme.md had some stuff added while Tim was adding his, so merge is failing. I tried sync it by edit Tim's changes but that didn't trick github :). Github says need use command line to fix the merge, but from work it doesn't look like I can get command line GIT to allow me hooked to external repository.

**Comment by eross529** [comment]
sorry meant Ahmad - my usual terrible typing skills

**Comment by fahmyboy** [comment]
I am looking at it now. I guess I need to learn how to merge from the command prompt :) I'm excited ! I will try and get to this tonight

**Comment by eross529** [comment]
LOL sounds good

**Review by fahmyboy — APPROVED** [review]

**Pull request closed without merging**
